version: '1.0'
name: pipeline-20220529
displayName: 项目部署
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
    commitMessages:
      include:
        - ^wumei-deploy
stages:
  - name: stage-2c3f9607
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '8'
        mavenVersion: 3.6.1
        commands:
          - cd ./springboot
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_JAVA
            path:
              - ../document/java
        settings: []
        strategy:
          retry: '0'
  - name: stage-129078f0
    displayName: 发布-可无
    strategy: naturally
    trigger: auto
    executor:
      - kerwincui
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_JAVA
        artifactName: output
        strategy:
          retry: '0'
  - name: stage-b6625c4a
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: alicloud
        deployArtifact:
          - source: artifact
            name: output
            target: ~/gitee_go/deploy
            artifactRepository: release
            artifactName: output
            artifactVersion: latest
        script: |-
          # 请在此输入部署脚本，如启动Java应用如下
          # nohup java -jar test.jar > nohup.out &
           echo 'Hello Gitee!'
        strategy:
          retry: '0'
strategy:
  blocking: true
permissions:
  - role: admin
    members:
      - kerwincui
